#!/bin/bash

# Variables d'environnement pour la connexion à PostgreSQL
POSTGRESQL_ADDON_DB=${POSTGRESQL_ADDON_DB}
POSTGRESQL_ADDON_HOST=${POSTGRESQL_ADDON_HOST}
POSTGRESQL_ADDON_PASSWORD=${POSTGRESQL_ADDON_PASSWORD}
POSTGRESQL_ADDON_PORT=${POSTGRESQL_ADDON_PORT}
POSTGRESQL_ADDON_USER=${POSTGRESQL_ADDON_USER}

# Démarrer le conteneur Nextcloud avec les variables d'environnement
docker run -d -p 8080:80 \
  -e NEXTCLOUD_ADMIN_USER=${NEXT_USER} \
  -e NEXTCLOUD_ADMIN_PASSWORD=${NEXT_PSWD} \
  -e NEXTCLOUD_DB_TYPE=pgsql \
  -e NEXTCLOUD_DB_HOST=${POSTGRESQL_ADDON_HOST} \
  -e NEXTCLOUD_DB_PORT=${POSTGRESQL_ADDON_PORT} \
  -e NEXTCLOUD_DB_NAME=${POSTGRESQL_ADDON_DB} \
  -e NEXTCLOUD_DB_USER=${POSTGRESQL_ADDON_USER} \
  -e NEXTCLOUD_DB_PASSWORD=${POSTGRESQL_ADDON_PASSWORD} \
  nextcloud
