docker run -d -p 8080:80 \
  -e NEXTCLOUD_ADMIN_USER="$NEXT_USER" \
  -e NEXTCLOUD_ADMIN_PASSWORD="$NEXT_PSWD" \
  -e POSTGRES_DB="$POSTGRESQL_ADDON_DB" \
  -e POSTGRES_HOST="$POSTGRESQL_ADDON_HOST" \
  -e POSTGRES_PASSWORD="$POSTGRESQL_ADDON_PASSWORD" \
  -e POSTGRES_PORT="$POSTGRESQL_ADDON_PORT" \
  -e POSTGRES_USER="$POSTGRESQL_ADDON_USER" \
  nextcloud
